window.CONTENT_CONFIG = {
  storageKey: "homepage-content-v1",
  layoutStorageKey: "homepage-layout-v1",
  heroStorageKey: "homepage-hero-grid-v1",
  gridStorageKey: "homepage-news-grid-v1",
  defaultHeroBoxes: [
    { id: "hero-1", section: "NORTHEAST", title: "Preserving the memory of the Battle of Imphal.", summary: "A private archive of living history from Manipur's wartime landscape.", image: "images/505383798_10234027599329754_8249245958977938540_n.jpg", alt: "Arambam Angamba portrait" },
    { id: "hero-2", section: "ARCHIVE", title: "From object to evidence. From evidence to story.", summary: "Each artifact is treated not as decoration, but as a witness.", image: "images/466930999_18335865004146368_7575377668775702294_n.jpg", alt: "Museum space" },
    { id: "hero-3", section: "COLLECTION", title: "Relics displayed with restraint, dignity and context.", summary: "Recovered metal, equipment and wartime traces from historic ground.", image: "images/30714447_10214175829967927_165775283675201536_n.jpg", alt: "Field relics" }
  ],
  defaultGridBoxes: [
    { id: "grid-1", section: "FIELD RELICS", title: "Recovered metal and wartime traces", summary: "Equipment and artifacts recovered from the Imphal battlefield.", image: "images/30714447_10214175829967927_165775283675201536_n.jpg", alt: "Field relics" },
    { id: "grid-2", section: "PERSONAL OBJECTS", title: "Small objects, large human stories", summary: "Personal items that carry the weight of individual experiences.", image: "images/509907537_9798865930212242_4053852646581686902_n.jpg", alt: "Personal objects" },
    { id: "grid-3", section: "MUSEUM EXHIBITS", title: "Uniforms and interpreted material culture", summary: "Displays that contextualize the wartime experience.", image: "images/467490331_10231718808091416_7415891893858139362_n.jpg", alt: "Museum exhibits" },
    { id: "grid-4", section: "MECHANICAL REMAINS", title: "Fragments preserved as testimony", summary: "Mechanical remnants that speak to the scale of conflict.", image: "images/467595565_10231718808171418_3462304517268544010_n.jpg", alt: "Mechanical remains" },
    { id: "grid-5", section: "ARCHIVE ENCOUNTERS", title: "Keeping memory alive", summary: "Visitors, researchers and storytellers engaging with history.", image: "images/467524642_10231715525409351_4612654496623592331_n.jpg", alt: "Visitors" },
    { id: "grid-6", section: "BATTLEFIELD WALKS", title: "Guided trails through history", summary: "Walking the terrain where history remains present.", image: "images/467659712_10231716665877862_576293277394653817_n.jpg", alt: "Battlefield walks" }
  ],
  fields: [
    ["brand-title", "[data-text-key='brand-title']", "Brand Title", "text"],
    ["brand-subtitle", "[data-text-key='brand-subtitle']", "Brand Subtitle", "text"],
    ["hero-eyebrow", "[data-text-key='hero-eyebrow']", "Hero Eyebrow", "text"],
    ["hero-title", "[data-text-key='hero-title']", "Hero Headline", "textarea"],
    ["hero-bio-1", "[data-text-key='hero-bio-1']", "Hero Bio (Primary)", "textarea"],
    ["hero-bio-2", "[data-text-key='hero-bio-2']", "Hero Bio (Secondary)", "textarea"],
    ["hero-quote", "[data-text-key='hero-quote']", "Hero Quote", "textarea"],
    ["hero-name", "[data-text-key='hero-name']", "Portrait Name", "text"],
    ["hero-role", "[data-text-key='hero-role']", "Portrait Role", "text"],
    ["portrait", "[data-image-key='portrait']", "Portrait Image", "image"],
    ["mission-eyebrow", "[data-text-key='mission-eyebrow']", "Mission Eyebrow", "text"],
    ["mission-title", "[data-text-key='mission-title']", "Mission Headline", "textarea"],
    ["mission-text", "[data-text-key='mission-text']", "Mission Paragraph", "textarea"],
    ["collection-eyebrow", "[data-text-key='collection-eyebrow']", "Collection Eyebrow", "text"],
    ["collection-title", "[data-text-key='collection-title']", "Collection Headline", "textarea"],
    ["card-01-title", "[data-text-key='card-01-title']", "Card 1 Title", "text"],
    ["card-01-text", "[data-text-key='card-01-text']", "Card 1 Text", "textarea"],
    ["card-01", "[data-image-key='card-01']", "Card 1 Image", "image"],
    ["card-02-title", "[data-text-key='card-02-title']", "Card 2 Title", "text"],
    ["card-02-text", "[data-text-key='card-02-text']", "Card 2 Text", "textarea"],
    ["card-02", "[data-image-key='card-02']", "Card 2 Image", "image"],
    ["card-03-title", "[data-text-key='card-03-title']", "Card 3 Title", "text"],
    ["card-03-text", "[data-text-key='card-03-text']", "Card 3 Text", "textarea"],
    ["card-03", "[data-image-key='card-03']", "Card 3 Image", "image"],
    ["card-04-title", "[data-text-key='card-04-title']", "Card 4 Title", "text"],
    ["card-04-text", "[data-text-key='card-04-text']", "Card 4 Text", "textarea"],
    ["card-04", "[data-image-key='card-04']", "Card 4 Image", "image"],
    ["card-05-title", "[data-text-key='card-05-title']", "Card 5 Title", "text"],
    ["card-05-text", "[data-text-key='card-05-text']", "Card 5 Text", "textarea"],
    ["card-05", "[data-image-key='card-05']", "Card 5 Image", "image"],
    ["card-06-title", "[data-text-key='card-06-title']", "Card 6 Title", "text"],
    ["card-06-text", "[data-text-key='card-06-text']", "Card 6 Text", "textarea"],
    ["card-06", "[data-image-key='card-06']", "Card 6 Image", "image"],
    ["story-eyebrow", "[data-text-key='story-eyebrow']", "Story Eyebrow", "text"],
    ["story-title", "[data-text-key='story-title']", "Story Headline", "textarea"],
    ["story-text", "[data-text-key='story-text']", "Story Paragraph", "textarea"],
    ["story-image", "[data-image-key='story-image']", "Story Image", "image"],
    ["stat-1-label", "[data-text-key='stat-1-label']", "Stat 1 Label", "text"],
    ["stat-1-value", "[data-text-key='stat-1-value']", "Stat 1 Value", "text"],
    ["stat-2-label", "[data-text-key='stat-2-label']", "Stat 2 Label", "text"],
    ["stat-2-value", "[data-text-key='stat-2-value']", "Stat 2 Value", "text"],
    ["stat-3-label", "[data-text-key='stat-3-label']", "Stat 3 Label", "text"],
    ["stat-3-value", "[data-text-key='stat-3-value']", "Stat 3 Value", "text"],
    ["guest-eyebrow", "[data-text-key='guest-eyebrow']", "Guestbook Eyebrow", "text"],
    ["guest-title", "[data-text-key='guest-title']", "Guestbook Headline", "textarea"],
    ["guest-text", "[data-text-key='guest-text']", "Guestbook Paragraph", "textarea"],
    ["footer-title", "[data-text-key='footer-title']", "Footer Title", "text"],
    ["footer-text", "[data-text-key='footer-text']", "Footer Text", "textarea"]
  ]
};
