import React from 'react';
import {describe,it,expect,vi,afterEach} from 'vitest';
import {render,screen,fireEvent,waitFor,cleanup,act} from '@testing-library/react';
import defaults from '../server/defaults.json';
import {Admin} from '../src/Admin';
import {Hero} from '../src/Hero';
import {Calendar} from '../src/Calendar';
import {api,upload} from '../src/api';
vi.mock('../src/api',async()=>{const actual=await vi.importActual('../src/api');return {...actual,api:vi.fn(),upload:vi.fn()}});
afterEach(()=>{cleanup();vi.clearAllMocks();vi.useRealTimers()});
const fixtures=()=>{api.mockImplementation(async(path)=>path==='/session'?{authenticated:true}:path==='/admin'?{content:structuredClone(defaults),bookings:[],guestbook:[]}:{today:'2026-10-05'});};
describe('Admin editing screens with isolated API fixtures',()=>{
 it('edits and saves the biography, preserving the rest of the content',async()=>{fixtures();render(<Admin/>);const input=await screen.findByLabelText('Biography heading');fireEvent.change(input,{target:{value:'Learning never stops.'}});fireEvent.click(screen.getByRole('button',{name:'Save changes'}));await waitFor(()=>expect(api).toHaveBeenCalledWith('/content',expect.objectContaining({title:'Battle of Imphal 1944',bioTitle:'Learning never stops.'})));});
 it('adds, uploads and reorders hero media',async()=>{fixtures();upload.mockResolvedValue('/uploads/test.mp4');render(<Admin/>);fireEvent.click(await screen.findByRole('button',{name:'Hero media'}));fireEvent.click(screen.getByRole('button',{name:'Add hero slide'}));expect(screen.getByRole('heading',{name:'Slide 4'})).toBeTruthy();const files=document.querySelectorAll('input[type=file]');fireEvent.change(files[3],{target:{files:[new File(['test'],'test.mp4',{type:'video/mp4'})]}});await screen.findByText('Uploaded. Save changes to publish this media.');fireEvent.click(screen.getByRole('button',{name:'Move slide 4 up'}));fireEvent.click(screen.getByRole('button',{name:'Save changes'}));await waitFor(()=>expect(api).toHaveBeenCalledWith('/content',expect.objectContaining({slides:expect.arrayContaining([expect.objectContaining({src:'/uploads/test.mp4',type:'video'})])})));});
 it('adds gallery images, blocks a date, and saves donation settings',async()=>{fixtures();render(<Admin/>);fireEvent.click(await screen.findByRole('button',{name:'Gallery'}));fireEvent.click(screen.getByRole('button',{name:'Add photograph'}));expect(screen.getByRole('heading',{name:'Photograph 4'})).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:'Tours & calendar'}));fireEvent.click(screen.getByRole('button',{name:'2026-10-20'}));fireEvent.click(screen.getByRole('button',{name:'Settings'}));fireEvent.change(screen.getByLabelText('Donation payment link (HTTPS)'),{target:{value:'https://example.com/donate'}});fireEvent.click(screen.getByRole('button',{name:'Save changes'}));await waitFor(()=>expect(api).toHaveBeenCalledWith('/content',expect.objectContaining({blockedDates:['2026-10-20'],donationUrl:'https://example.com/donate',gallery:expect.any(Array)})));});
 it('shows signed-out password form without exposing content',async()=>{api.mockResolvedValue({authenticated:false});render(<Admin/>);await screen.findByLabelText('Administrator password');expect(screen.queryByLabelText('Biography heading')).toBeNull();});
});
describe('Media and calendar behavior',()=>{
 it('advances images, pauses, changes interval and navigates backwards',()=>{vi.useFakeTimers();render(<Hero content={defaults}/>);act(()=>vi.advanceTimersByTime(4000));expect(screen.getByText('Objects, memories and the stories between')).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:'Pause slideshow'}));act(()=>vi.advanceTimersByTime(9000));expect(screen.getByText('Objects, memories and the stories between')).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:'Previous slide'}));expect(screen.getByText('Manipur, through the seasons')).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:'Slide interval'}));fireEvent.click(screen.getByRole('button',{name:'8 seconds'}));expect(screen.getByText('8s')).toBeTruthy();});
 it('waits 3 seconds for video, does not advance until it ends, then resumes photos',async()=>{vi.useFakeTimers();vi.spyOn(HTMLMediaElement.prototype,'play').mockResolvedValue();vi.spyOn(HTMLMediaElement.prototype,'pause').mockImplementation(()=>{});const content={...defaults,slides:[{id:'v',type:'video',src:'/test.mp4',caption:'Test film'},...defaults.slides]};render(<Hero content={content}/>);expect(screen.getByText('Video starts in 3s · Muted')).toBeTruthy();for(let i=0;i<3;i++)act(()=>vi.advanceTimersByTime(1000));expect(HTMLMediaElement.prototype.play).toHaveBeenCalled();act(()=>vi.advanceTimersByTime(10000));expect(screen.getByText('Test film')).toBeTruthy();fireEvent.ended(document.querySelector('video'));expect(screen.getByText('Manipur, through the seasons')).toBeTruthy();});
 it('disables past and unavailable dates and exposes the selected date',()=>{const onChange=vi.fn();render(<Calendar today="2026-10-05" value="2026-10-20" unavailable={['2026-10-22']} onChange={onChange}/>);expect(screen.getByRole('button',{name:'2026-10-01'}).disabled).toBe(true);expect(screen.getByRole('button',{name:'2026-10-22 unavailable'}).disabled).toBe(true);fireEvent.click(screen.getByRole('button',{name:'2026-10-21'}));expect(onChange).toHaveBeenCalledWith('2026-10-21');});
});
